// Code generated by protoc-gen-go. DO NOT EDIT.
// source: candlestick/v1/candlestick_service.proto

package candlestick

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CandlestickRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OpenTime             int64    `protobuf:"varint,4,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	TimeFrame            string   `protobuf:"bytes,5,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandlestickRequest) Reset()         { *m = CandlestickRequest{} }
func (m *CandlestickRequest) String() string { return proto.CompactTextString(m) }
func (*CandlestickRequest) ProtoMessage()    {}
func (*CandlestickRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb33fc287a619be7, []int{0}
}

func (m *CandlestickRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandlestickRequest.Unmarshal(m, b)
}
func (m *CandlestickRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandlestickRequest.Marshal(b, m, deterministic)
}
func (m *CandlestickRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandlestickRequest.Merge(m, src)
}
func (m *CandlestickRequest) XXX_Size() int {
	return xxx_messageInfo_CandlestickRequest.Size(m)
}
func (m *CandlestickRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CandlestickRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CandlestickRequest proto.InternalMessageInfo

func (m *CandlestickRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CandlestickRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *CandlestickRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CandlestickRequest) GetOpenTime() int64 {
	if m != nil {
		return m.OpenTime
	}
	return 0
}

func (m *CandlestickRequest) GetTimeFrame() string {
	if m != nil {
		return m.TimeFrame
	}
	return ""
}

type CandlestickResponse struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Candlestick          *Candlestick `protobuf:"bytes,2,opt,name=candlestick,proto3" json:"candlestick,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandlestickResponse) Reset()         { *m = CandlestickResponse{} }
func (m *CandlestickResponse) String() string { return proto.CompactTextString(m) }
func (*CandlestickResponse) ProtoMessage()    {}
func (*CandlestickResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb33fc287a619be7, []int{1}
}

func (m *CandlestickResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandlestickResponse.Unmarshal(m, b)
}
func (m *CandlestickResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandlestickResponse.Marshal(b, m, deterministic)
}
func (m *CandlestickResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandlestickResponse.Merge(m, src)
}
func (m *CandlestickResponse) XXX_Size() int {
	return xxx_messageInfo_CandlestickResponse.Size(m)
}
func (m *CandlestickResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandlestickResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandlestickResponse proto.InternalMessageInfo

func (m *CandlestickResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CandlestickResponse) GetCandlestick() *Candlestick {
	if m != nil {
		return m.Candlestick
	}
	return nil
}

type CandlesticksRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TimeFrame            string   `protobuf:"bytes,4,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	From                 int64    `protobuf:"varint,5,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64    `protobuf:"varint,6,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandlesticksRequest) Reset()         { *m = CandlesticksRequest{} }
func (m *CandlesticksRequest) String() string { return proto.CompactTextString(m) }
func (*CandlesticksRequest) ProtoMessage()    {}
func (*CandlesticksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb33fc287a619be7, []int{2}
}

func (m *CandlesticksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandlesticksRequest.Unmarshal(m, b)
}
func (m *CandlesticksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandlesticksRequest.Marshal(b, m, deterministic)
}
func (m *CandlesticksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandlesticksRequest.Merge(m, src)
}
func (m *CandlesticksRequest) XXX_Size() int {
	return xxx_messageInfo_CandlesticksRequest.Size(m)
}
func (m *CandlesticksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CandlesticksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CandlesticksRequest proto.InternalMessageInfo

func (m *CandlesticksRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CandlesticksRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *CandlesticksRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CandlesticksRequest) GetTimeFrame() string {
	if m != nil {
		return m.TimeFrame
	}
	return ""
}

func (m *CandlesticksRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *CandlesticksRequest) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func init() {
	proto.RegisterType((*CandlestickRequest)(nil), "candlestick.v1.CandlestickRequest")
	proto.RegisterType((*CandlestickResponse)(nil), "candlestick.v1.CandlestickResponse")
	proto.RegisterType((*CandlesticksRequest)(nil), "candlestick.v1.CandlesticksRequest")
}

func init() {
	proto.RegisterFile("candlestick/v1/candlestick_service.proto", fileDescriptor_bb33fc287a619be7)
}

var fileDescriptor_bb33fc287a619be7 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x86, 0xb1, 0x4d, 0x11, 0x2c, 0x12, 0x87, 0x6d, 0x85, 0x5c, 0xa3, 0x4a, 0xc8, 0xbd, 0x70,
	0xb2, 0x0b, 0x3d, 0x56, 0xbd, 0xd0, 0x0a, 0x2e, 0x3d, 0x20, 0x97, 0x53, 0x22, 0xc5, 0xf2, 0xc7,
	0x62, 0x56, 0xf1, 0x7a, 0x1c, 0xef, 0x42, 0xc2, 0xff, 0xc8, 0x29, 0xca, 0x8f, 0x8d, 0xbc, 0xce,
	0xc7, 0x9a, 0x28, 0x4e, 0x0e, 0xdc, 0x3c, 0xef, 0xcc, 0x78, 0xe6, 0x79, 0x47, 0x8b, 0x26, 0x51,
	0x90, 0xc5, 0x29, 0xe1, 0x82, 0x46, 0x97, 0xee, 0x7e, 0xea, 0x2a, 0xa1, 0xcf, 0x49, 0xb1, 0xa7,
	0x11, 0x71, 0xf2, 0x02, 0x04, 0xe0, 0x81, 0x92, 0x72, 0xf6, 0x53, 0x6b, 0xfc, 0x76, 0x67, 0xd5,
	0x61, 0xdf, 0x6a, 0x08, 0xff, 0x79, 0x51, 0x3d, 0x72, 0xb5, 0x23, 0x5c, 0xe0, 0x01, 0xd2, 0x69,
	0x6c, 0x6a, 0x63, 0x6d, 0xd2, 0xf3, 0x74, 0x1a, 0x63, 0x0b, 0x75, 0xc9, 0x4d, 0xb4, 0x0d, 0xb2,
	0x84, 0x98, 0xba, 0x54, 0x9f, 0x63, 0x3c, 0x44, 0x1d, 0x7e, 0x60, 0x21, 0xa4, 0xa6, 0x21, 0x33,
	0x8f, 0x11, 0x1e, 0xa1, 0x1e, 0xe4, 0x24, 0xf3, 0x05, 0x65, 0xc4, 0x6c, 0x8f, 0xb5, 0x89, 0xe1,
	0x75, 0x4b, 0x61, 0x4d, 0x19, 0xc1, 0xdf, 0x10, 0x2a, 0x75, 0x7f, 0x53, 0x04, 0x8c, 0x98, 0x9f,
	0x64, 0x63, 0xaf, 0x54, 0x16, 0xa5, 0x60, 0xc7, 0xe8, 0x73, 0x6d, 0x2b, 0x9e, 0x43, 0xc6, 0xc9,
	0xab, 0xb5, 0x7e, 0xa3, 0xbe, 0x82, 0x24, 0x37, 0xeb, 0xcf, 0x46, 0x4e, 0xdd, 0x05, 0x47, 0xfd,
	0x93, 0x5a, 0x6f, 0xdf, 0x6b, 0xb5, 0x31, 0xfc, 0x94, 0xf4, 0x75, 0xc0, 0xf6, 0x11, 0x20, 0xc6,
	0xa8, 0xbd, 0x29, 0x80, 0x49, 0x72, 0xc3, 0x93, 0xdf, 0xe5, 0x58, 0x01, 0x66, 0x47, 0x2a, 0xba,
	0x80, 0xd9, 0x9d, 0x51, 0xbb, 0xcd, 0xff, 0xea, 0xd4, 0x78, 0x83, 0xbe, 0x2e, 0x89, 0x50, 0x12,
	0xf3, 0x43, 0x69, 0xe9, 0x0a, 0x68, 0x26, 0xb0, 0xdd, 0x04, 0x5f, 0xe1, 0x59, 0xdf, 0x1b, 0x6b,
	0x2a, 0xab, 0xed, 0x16, 0xbe, 0x40, 0xc3, 0x15, 0xa4, 0xa9, 0x6a, 0xd0, 0xa2, 0x00, 0xb6, 0x06,
	0xdc, 0xf4, 0x83, 0x27, 0x13, 0xad, 0xa6, 0x33, 0xd8, 0xad, 0x1f, 0x1a, 0xf6, 0x11, 0x5e, 0x12,
	0xf1, 0x2f, 0xe0, 0x2a, 0xcb, 0x29, 0x01, 0xce, 0xd1, 0x97, 0x12, 0xe0, 0x68, 0x02, 0xff, 0xd0,
	0x88, 0xf7, 0xb6, 0x9f, 0x2f, 0xce, 0xfe, 0x26, 0x54, 0x6c, 0x77, 0xa1, 0x13, 0x01, 0x73, 0xaf,
	0x83, 0x22, 0x4f, 0x0a, 0x57, 0xc4, 0x61, 0xe0, 0x47, 0xc0, 0x18, 0x64, 0x6e, 0x02, 0xae, 0x7c,
	0x62, 0x11, 0xa4, 0x6e, 0xfd, 0x19, 0xfe, 0x52, 0xc2, 0xb0, 0x23, 0x8b, 0x7e, 0x3e, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0xd1, 0x0f, 0x5a, 0xe5, 0x03, 0x00, 0x00,
}
