// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/v1/wallet.proto

package wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SimpleWallet struct {
	WalletId             string             `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Exchange             string             `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Assets               map[string]float64 `protobuf:"bytes,3,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	BaseAsset            float64            `protobuf:"fixed64,4,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	BaseAssetName        string             `protobuf:"bytes,5,opt,name=baseAssetName,proto3" json:"baseAssetName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SimpleWallet) Reset()         { *m = SimpleWallet{} }
func (m *SimpleWallet) String() string { return proto.CompactTextString(m) }
func (*SimpleWallet) ProtoMessage()    {}
func (*SimpleWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a45fb539ff6b1e, []int{0}
}

func (m *SimpleWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleWallet.Unmarshal(m, b)
}
func (m *SimpleWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleWallet.Marshal(b, m, deterministic)
}
func (m *SimpleWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleWallet.Merge(m, src)
}
func (m *SimpleWallet) XXX_Size() int {
	return xxx_messageInfo_SimpleWallet.Size(m)
}
func (m *SimpleWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleWallet.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleWallet proto.InternalMessageInfo

func (m *SimpleWallet) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

func (m *SimpleWallet) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *SimpleWallet) GetAssets() map[string]float64 {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *SimpleWallet) GetBaseAsset() float64 {
	if m != nil {
		return m.BaseAsset
	}
	return 0
}

func (m *SimpleWallet) GetBaseAssetName() string {
	if m != nil {
		return m.BaseAssetName
	}
	return ""
}

type UserWallets struct {
	UserId               string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Wallets              []*SimpleWallet `protobuf:"bytes,2,rep,name=wallets,proto3" json:"wallets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserWallets) Reset()         { *m = UserWallets{} }
func (m *UserWallets) String() string { return proto.CompactTextString(m) }
func (*UserWallets) ProtoMessage()    {}
func (*UserWallets) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a45fb539ff6b1e, []int{1}
}

func (m *UserWallets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWallets.Unmarshal(m, b)
}
func (m *UserWallets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWallets.Marshal(b, m, deterministic)
}
func (m *UserWallets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWallets.Merge(m, src)
}
func (m *UserWallets) XXX_Size() int {
	return xxx_messageInfo_UserWallets.Size(m)
}
func (m *UserWallets) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWallets.DiscardUnknown(m)
}

var xxx_messageInfo_UserWallets proto.InternalMessageInfo

func (m *UserWallets) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserWallets) GetWallets() []*SimpleWallet {
	if m != nil {
		return m.Wallets
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleWallet)(nil), "wallet.v1.SimpleWallet")
	proto.RegisterMapType((map[string]float64)(nil), "wallet.v1.SimpleWallet.AssetsEntry")
	proto.RegisterType((*UserWallets)(nil), "wallet.v1.UserWallets")
}

func init() {
	proto.RegisterFile("wallet/v1/wallet.proto", fileDescriptor_73a45fb539ff6b1e)
}

var fileDescriptor_73a45fb539ff6b1e = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xe5, 0xf4, 0xdb, 0x5f, 0xd7, 0x2f, 0x12, 0xb2, 0x10, 0xb5, 0x8a, 0x90, 0xaa, 0xc2,
	0xd0, 0x29, 0x56, 0x61, 0x81, 0x96, 0x05, 0x24, 0x86, 0x2e, 0x0c, 0x41, 0x08, 0xc1, 0x12, 0x39,
	0x89, 0x95, 0x46, 0x24, 0x71, 0x64, 0x3b, 0x29, 0xdd, 0xf9, 0xc3, 0x51, 0xec, 0x34, 0x94, 0x81,
	0xed, 0x3e, 0xef, 0x2e, 0x79, 0xf7, 0x7c, 0x70, 0xba, 0x65, 0x69, 0xca, 0x35, 0xad, 0x16, 0xd4,
	0x56, 0x6e, 0x21, 0x85, 0x16, 0x78, 0xd8, 0x50, 0xb5, 0x98, 0x7d, 0x39, 0xf0, 0xff, 0x39, 0xc9,
	0x8a, 0x94, 0xbf, 0x1a, 0x0d, 0x9f, 0x41, 0xd3, 0xf5, 0x93, 0x88, 0xa0, 0x29, 0x9a, 0x0f, 0xbd,
	0x81, 0x15, 0xd6, 0x11, 0x9e, 0xc0, 0x80, 0x7f, 0x86, 0x1b, 0x96, 0xc7, 0x9c, 0x38, 0xb6, 0xb7,
	0x67, 0xbc, 0x82, 0x1e, 0x53, 0x8a, 0x6b, 0x45, 0x3a, 0xd3, 0xce, 0x7c, 0x74, 0x75, 0xe1, 0xb6,
	0x2e, 0xee, 0xa1, 0x83, 0x7b, 0x6f, 0xa6, 0x1e, 0x73, 0x2d, 0x77, 0x5e, 0xf3, 0x09, 0x3e, 0x07,
	0x08, 0x98, 0xe2, 0xbe, 0x41, 0xf2, 0x6f, 0x8a, 0xe6, 0xc8, 0x1b, 0xd6, 0x8a, 0x19, 0xc6, 0x97,
	0x70, 0xd4, 0xc2, 0x13, 0xcb, 0x38, 0xe9, 0x1a, 0xf3, 0xdf, 0xe2, 0xe4, 0x16, 0x46, 0x07, 0xff,
	0xc6, 0xc7, 0xd0, 0xf9, 0xe0, 0xbb, 0x26, 0x43, 0x5d, 0xe2, 0x13, 0xe8, 0x56, 0x2c, 0x2d, 0xed,
	0xee, 0xc8, 0xb3, 0xb0, 0x74, 0x6e, 0xd0, 0xec, 0x0d, 0x46, 0x2f, 0x8a, 0x4b, 0xbb, 0xa1, 0xc2,
	0x63, 0xe8, 0x97, 0x8a, 0xcb, 0x9f, 0x27, 0xe8, 0xd5, 0xb8, 0x8e, 0xf0, 0x02, 0xfa, 0x36, 0x95,
	0x22, 0x8e, 0x49, 0x39, 0xfe, 0x23, 0xa5, 0xb7, 0x9f, 0x7b, 0xb8, 0x7b, 0x5f, 0xc6, 0x89, 0xde,
	0x94, 0x81, 0x1b, 0x8a, 0x8c, 0x6e, 0x99, 0x2c, 0x62, 0x49, 0x75, 0x14, 0x30, 0x3f, 0x14, 0x59,
	0x26, 0x72, 0x1a, 0x0b, 0x6a, 0xce, 0x12, 0x8a, 0x94, 0xb6, 0x07, 0x5b, 0xd9, 0x2a, 0xe8, 0x99,
	0xd6, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x4a, 0xbe, 0xc9, 0xcb, 0x01, 0x00, 0x00,
}
