// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/v1/wallet_service.proto

package wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateWalletRequest struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string             `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string             `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Assets               map[string]float64 `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateWalletRequest) Reset()         { *m = CreateWalletRequest{} }
func (m *CreateWalletRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletRequest) ProtoMessage()    {}
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5cbb926e133f949, []int{0}
}

func (m *CreateWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletRequest.Unmarshal(m, b)
}
func (m *CreateWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletRequest.Marshal(b, m, deterministic)
}
func (m *CreateWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletRequest.Merge(m, src)
}
func (m *CreateWalletRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletRequest.Size(m)
}
func (m *CreateWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletRequest proto.InternalMessageInfo

func (m *CreateWalletRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateWalletRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateWalletRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *CreateWalletRequest) GetAssets() map[string]float64 {
	if m != nil {
		return m.Assets
	}
	return nil
}

type GetWalletRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId             string   `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletRequest) Reset()         { *m = GetWalletRequest{} }
func (m *GetWalletRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletRequest) ProtoMessage()    {}
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5cbb926e133f949, []int{1}
}

func (m *GetWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletRequest.Unmarshal(m, b)
}
func (m *GetWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletRequest.Merge(m, src)
}
func (m *GetWalletRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletRequest.Size(m)
}
func (m *GetWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletRequest proto.InternalMessageInfo

func (m *GetWalletRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetWalletRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *GetWalletRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetWalletRequest) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

type GetWalletResponse struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wallet               *SimpleWallet `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetWalletResponse) Reset()         { *m = GetWalletResponse{} }
func (m *GetWalletResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletResponse) ProtoMessage()    {}
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5cbb926e133f949, []int{2}
}

func (m *GetWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletResponse.Unmarshal(m, b)
}
func (m *GetWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletResponse.Marshal(b, m, deterministic)
}
func (m *GetWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletResponse.Merge(m, src)
}
func (m *GetWalletResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletResponse.Size(m)
}
func (m *GetWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletResponse proto.InternalMessageInfo

func (m *GetWalletResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetWalletResponse) GetWallet() *SimpleWallet {
	if m != nil {
		return m.Wallet
	}
	return nil
}

type GetUserWalletsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserWalletsRequest) Reset()         { *m = GetUserWalletsRequest{} }
func (m *GetUserWalletsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserWalletsRequest) ProtoMessage()    {}
func (*GetUserWalletsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5cbb926e133f949, []int{3}
}

func (m *GetUserWalletsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserWalletsRequest.Unmarshal(m, b)
}
func (m *GetUserWalletsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserWalletsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserWalletsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserWalletsRequest.Merge(m, src)
}
func (m *GetUserWalletsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserWalletsRequest.Size(m)
}
func (m *GetUserWalletsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserWalletsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserWalletsRequest proto.InternalMessageInfo

func (m *GetUserWalletsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserWalletsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserWalletsResponse struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wallet               *UserWallets `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserWalletsResponse) Reset()         { *m = GetUserWalletsResponse{} }
func (m *GetUserWalletsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserWalletsResponse) ProtoMessage()    {}
func (*GetUserWalletsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5cbb926e133f949, []int{4}
}

func (m *GetUserWalletsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserWalletsResponse.Unmarshal(m, b)
}
func (m *GetUserWalletsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserWalletsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserWalletsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserWalletsResponse.Merge(m, src)
}
func (m *GetUserWalletsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserWalletsResponse.Size(m)
}
func (m *GetUserWalletsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserWalletsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserWalletsResponse proto.InternalMessageInfo

func (m *GetUserWalletsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserWalletsResponse) GetWallet() *UserWallets {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateWalletRequest)(nil), "wallet.v1.CreateWalletRequest")
	proto.RegisterMapType((map[string]float64)(nil), "wallet.v1.CreateWalletRequest.AssetsEntry")
	proto.RegisterType((*GetWalletRequest)(nil), "wallet.v1.GetWalletRequest")
	proto.RegisterType((*GetWalletResponse)(nil), "wallet.v1.GetWalletResponse")
	proto.RegisterType((*GetUserWalletsRequest)(nil), "wallet.v1.GetUserWalletsRequest")
	proto.RegisterType((*GetUserWalletsResponse)(nil), "wallet.v1.GetUserWalletsResponse")
}

func init() {
	proto.RegisterFile("wallet/v1/wallet_service.proto", fileDescriptor_f5cbb926e133f949)
}

var fileDescriptor_f5cbb926e133f949 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x76, 0x31, 0x64, 0x52, 0xaa, 0xb2, 0x40, 0x6a, 0xb9, 0xa8, 0x0a, 0x3e, 0x55, 0x1c,
	0xbc, 0x6a, 0xb8, 0x40, 0xe1, 0x00, 0x05, 0x54, 0x2a, 0x24, 0x0e, 0x2e, 0xa8, 0x88, 0x4b, 0xe4,
	0xd8, 0x23, 0xd7, 0xc2, 0xf6, 0x9a, 0xdd, 0xb5, 0x4b, 0xbf, 0x92, 0x33, 0x7f, 0x83, 0xb2, 0xeb,
	0x5a, 0x9b, 0xa4, 0x44, 0xa0, 0xde, 0x76, 0xde, 0xbc, 0x79, 0xf3, 0x66, 0xc6, 0x86, 0xbd, 0x8b,
	0xb8, 0x28, 0x50, 0xd2, 0xf6, 0x80, 0xea, 0xd7, 0x54, 0x20, 0x6f, 0xf3, 0x04, 0xc3, 0x9a, 0x33,
	0xc9, 0xc8, 0x40, 0xa3, 0x61, 0x7b, 0xe0, 0x8f, 0x96, 0xa9, 0x9a, 0x12, 0xfc, 0xb6, 0xe0, 0xc1,
	0x5b, 0x8e, 0xb1, 0xc4, 0x33, 0x05, 0x47, 0xf8, 0xa3, 0x41, 0x21, 0xc9, 0x16, 0xd8, 0x79, 0xea,
	0x59, 0x63, 0x6b, 0x7f, 0x10, 0xd9, 0x79, 0x4a, 0x76, 0xe0, 0x4e, 0x23, 0x90, 0x4f, 0xf3, 0xd4,
	0xb3, 0x15, 0xe8, 0xce, 0xc3, 0x93, 0x94, 0xf8, 0x70, 0x17, 0x7f, 0x26, 0xe7, 0x71, 0x95, 0xa1,
	0xe7, 0xa8, 0x4c, 0x1f, 0x93, 0x23, 0x70, 0x63, 0x21, 0x50, 0x0a, 0x6f, 0x63, 0xec, 0xec, 0x0f,
	0x27, 0x4f, 0xc3, 0xde, 0x50, 0x78, 0x4d, 0xd3, 0xf0, 0x8d, 0x22, 0xbf, 0xaf, 0x24, 0xbf, 0x8c,
	0xba, 0x4a, 0xff, 0x05, 0x0c, 0x0d, 0x98, 0x6c, 0x83, 0xf3, 0x1d, 0x2f, 0x3b, 0x63, 0xf3, 0x27,
	0x79, 0x08, 0xb7, 0xdb, 0xb8, 0x68, 0x50, 0xf9, 0xb2, 0x22, 0x1d, 0x1c, 0xda, 0xcf, 0xad, 0x40,
	0xc2, 0xf6, 0x31, 0xca, 0xf5, 0x73, 0x99, 0xf6, 0xed, 0x25, 0xfb, 0xc6, 0xcc, 0xce, 0xc2, 0xcc,
	0xbb, 0xd0, 0x6d, 0x76, 0x9e, 0xda, 0xd0, 0x55, 0x1a, 0x38, 0x49, 0x83, 0xcf, 0x70, 0xdf, 0xe8,
	0x2a, 0x6a, 0x56, 0x09, 0x5c, 0x69, 0x4b, 0xc1, 0xd5, 0x05, 0x4a, 0x79, 0x38, 0xd9, 0x31, 0x36,
	0x73, 0x9a, 0x97, 0x75, 0x71, 0xb5, 0x99, 0x8e, 0x16, 0xbc, 0x86, 0x47, 0xc7, 0x28, 0xbf, 0x08,
	0xe4, 0x3a, 0x21, 0xfe, 0xf7, 0x50, 0xc1, 0x57, 0x18, 0x2d, 0x2b, 0xfc, 0xc5, 0x5c, 0xd8, 0x9b,
	0xb3, 0x95, 0xb9, 0x91, 0x61, 0xce, 0xac, 0xef, 0x58, 0x93, 0x5f, 0x36, 0xdc, 0xd3, 0xd8, 0xa9,
	0xfe, 0xfc, 0xc8, 0x27, 0xd8, 0x34, 0xef, 0x4b, 0xf6, 0xd6, 0x1f, 0xde, 0x7f, 0x6c, 0xe4, 0x57,
	0x96, 0x17, 0xdc, 0x22, 0x1f, 0x61, 0xf3, 0x1d, 0x16, 0xd8, 0xeb, 0xed, 0x5e, 0xcf, 0xff, 0x37,
	0xb1, 0x0f, 0x30, 0xe8, 0xe1, 0x9b, 0x29, 0x9d, 0xc1, 0xd6, 0xe2, 0x4a, 0xc9, 0x78, 0xb1, 0x62,
	0xf5, 0x5e, 0xfe, 0x93, 0x35, 0x8c, 0x2b, 0xe1, 0xa3, 0x57, 0xdf, 0x0e, 0xb3, 0x5c, 0x9e, 0x37,
	0xb3, 0x30, 0x61, 0x25, 0xbd, 0x88, 0x79, 0x9d, 0x71, 0x2a, 0xd3, 0x59, 0x3c, 0x4d, 0x58, 0x59,
	0xb2, 0x8a, 0x66, 0x8c, 0xaa, 0xff, 0x37, 0x61, 0x05, 0xed, 0xff, 0xec, 0x97, 0xfa, 0x35, 0x73,
	0x55, 0xea, 0xd9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x07, 0x45, 0x07, 0x1f, 0x04, 0x00,
	0x00,
}
