// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet/v1/wallet.proto

package wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WalletDescriptor struct {
	WalletId             string             `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Exchange             string             `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Assests              map[string]float64 `protobuf:"bytes,3,rep,name=assests,proto3" json:"assests,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WalletDescriptor) Reset()         { *m = WalletDescriptor{} }
func (m *WalletDescriptor) String() string { return proto.CompactTextString(m) }
func (*WalletDescriptor) ProtoMessage()    {}
func (*WalletDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a45fb539ff6b1e, []int{0}
}

func (m *WalletDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletDescriptor.Unmarshal(m, b)
}
func (m *WalletDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletDescriptor.Marshal(b, m, deterministic)
}
func (m *WalletDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletDescriptor.Merge(m, src)
}
func (m *WalletDescriptor) XXX_Size() int {
	return xxx_messageInfo_WalletDescriptor.Size(m)
}
func (m *WalletDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_WalletDescriptor proto.InternalMessageInfo

func (m *WalletDescriptor) GetWalletId() string {
	if m != nil {
		return m.WalletId
	}
	return ""
}

func (m *WalletDescriptor) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *WalletDescriptor) GetAssests() map[string]float64 {
	if m != nil {
		return m.Assests
	}
	return nil
}

type UserWallet struct {
	UserId               string              `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Wallets              []*WalletDescriptor `protobuf:"bytes,2,rep,name=wallets,proto3" json:"wallets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserWallet) Reset()         { *m = UserWallet{} }
func (m *UserWallet) String() string { return proto.CompactTextString(m) }
func (*UserWallet) ProtoMessage()    {}
func (*UserWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a45fb539ff6b1e, []int{1}
}

func (m *UserWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWallet.Unmarshal(m, b)
}
func (m *UserWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWallet.Marshal(b, m, deterministic)
}
func (m *UserWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWallet.Merge(m, src)
}
func (m *UserWallet) XXX_Size() int {
	return xxx_messageInfo_UserWallet.Size(m)
}
func (m *UserWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWallet.DiscardUnknown(m)
}

var xxx_messageInfo_UserWallet proto.InternalMessageInfo

func (m *UserWallet) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserWallet) GetWallets() []*WalletDescriptor {
	if m != nil {
		return m.Wallets
	}
	return nil
}

func init() {
	proto.RegisterType((*WalletDescriptor)(nil), "wallet.v1.WalletDescriptor")
	proto.RegisterMapType((map[string]float64)(nil), "wallet.v1.WalletDescriptor.AssestsEntry")
	proto.RegisterType((*UserWallet)(nil), "wallet.v1.UserWallet")
}

func init() {
	proto.RegisterFile("wallet/v1/wallet.proto", fileDescriptor_73a45fb539ff6b1e)
}

var fileDescriptor_73a45fb539ff6b1e = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x49, 0x8b, 0xeb, 0xf6, 0xd7, 0xc3, 0x08, 0xa2, 0x65, 0xbb, 0x8c, 0x9d, 0x7a, 0x4a,
	0x98, 0x22, 0x48, 0xf5, 0xe2, 0xd0, 0xc3, 0xae, 0x05, 0x11, 0x44, 0x18, 0x69, 0x1a, 0xba, 0x62,
	0xdb, 0x94, 0x24, 0xed, 0xdc, 0x67, 0xf4, 0x4b, 0xc9, 0x9a, 0xb6, 0x8a, 0x87, 0xdd, 0xde, 0xaf,
	0xef, 0x95, 0xf7, 0xf2, 0x87, 0xab, 0x3d, 0xcb, 0x73, 0x61, 0x68, 0xb3, 0xa2, 0x56, 0x91, 0x4a,
	0x49, 0x23, 0xf1, 0xa4, 0xa3, 0x66, 0xb5, 0xfc, 0x46, 0x30, 0x7d, 0x6b, 0xe9, 0x59, 0x68, 0xae,
	0xb2, 0xca, 0x48, 0x85, 0xe7, 0xd0, 0x25, 0xb6, 0x59, 0xe2, 0xa3, 0x05, 0x0a, 0x26, 0xd1, 0xd8,
	0x7e, 0xd8, 0x24, 0x78, 0x06, 0x63, 0xf1, 0xc5, 0x77, 0xac, 0x4c, 0x85, 0xef, 0x58, 0xaf, 0x67,
	0xbc, 0x06, 0x8f, 0x69, 0x2d, 0xb4, 0xd1, 0xbe, 0xbb, 0x70, 0x83, 0xf3, 0x9b, 0x80, 0x0c, 0x55,
	0xe4, 0x7f, 0x0d, 0x79, 0xb2, 0xd1, 0x97, 0xd2, 0xa8, 0x43, 0xd4, 0xff, 0x38, 0x0b, 0xe1, 0xe2,
	0xaf, 0x81, 0xa7, 0xe0, 0x7e, 0x8a, 0x43, 0x37, 0xe3, 0x28, 0xf1, 0x25, 0x9c, 0x35, 0x2c, 0xaf,
	0x6d, 0x3d, 0x8a, 0x2c, 0x84, 0xce, 0x3d, 0x5a, 0x7e, 0x00, 0xbc, 0x6a, 0xa1, 0x6c, 0x13, 0xbe,
	0x06, 0xaf, 0xd6, 0x42, 0xfd, 0x3e, 0x62, 0x74, 0xc4, 0x4d, 0x82, 0xef, 0xc0, 0xb3, 0xb3, 0xb4,
	0xef, 0xb4, 0x33, 0xe7, 0x27, 0x66, 0x46, 0x7d, 0x76, 0xfd, 0xf8, 0x1e, 0xa6, 0x99, 0xd9, 0xd5,
	0x31, 0xe1, 0xb2, 0xa0, 0x7b, 0xa6, 0xaa, 0x54, 0x51, 0x93, 0xc4, 0x6c, 0xcb, 0x65, 0x51, 0xc8,
	0x92, 0xa6, 0x92, 0xb6, 0x07, 0xe6, 0x32, 0xa7, 0xc3, 0xe9, 0x1f, 0xac, 0x8a, 0x47, 0xad, 0x75,
	0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xfd, 0xfb, 0x05, 0x95, 0x01, 0x00, 0x00,
}
