// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders/v1/orders_service.proto

package orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlaceOrderRequest struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string           `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCredentials      *UserCredentials `protobuf:"bytes,3,opt,name=user_credentials,json=userCredentials,proto3" json:"user_credentials,omitempty"`
	Order                *CreateOrder     `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{0}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlaceOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PlaceOrderRequest) GetUserCredentials() *UserCredentials {
	if m != nil {
		return m.UserCredentials
	}
	return nil
}

func (m *PlaceOrderRequest) GetOrder() *CreateOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderStatusRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCredentials      *UserCredentials     `protobuf:"bytes,3,opt,name=user_credentials,json=userCredentials,proto3" json:"user_credentials,omitempty"`
	OrderDescriptor      *OrderDescriptorType `protobuf:"bytes,4,opt,name=order_descriptor,json=orderDescriptor,proto3" json:"order_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderStatusRequest) Reset()         { *m = OrderStatusRequest{} }
func (m *OrderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*OrderStatusRequest) ProtoMessage()    {}
func (*OrderStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{1}
}

func (m *OrderStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusRequest.Unmarshal(m, b)
}
func (m *OrderStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusRequest.Marshal(b, m, deterministic)
}
func (m *OrderStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusRequest.Merge(m, src)
}
func (m *OrderStatusRequest) XXX_Size() int {
	return xxx_messageInfo_OrderStatusRequest.Size(m)
}
func (m *OrderStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusRequest proto.InternalMessageInfo

func (m *OrderStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderStatusRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderStatusRequest) GetUserCredentials() *UserCredentials {
	if m != nil {
		return m.UserCredentials
	}
	return nil
}

func (m *OrderStatusRequest) GetOrderDescriptor() *OrderDescriptorType {
	if m != nil {
		return m.OrderDescriptor
	}
	return nil
}

type OrderStatusResponse struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserCredentials      *UserCredentials      `protobuf:"bytes,3,opt,name=user_credentials,json=userCredentials,proto3" json:"user_credentials,omitempty"`
	Order                *OrderAndExchangeType `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OrderStatusResponse) Reset()         { *m = OrderStatusResponse{} }
func (m *OrderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*OrderStatusResponse) ProtoMessage()    {}
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{2}
}

func (m *OrderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatusResponse.Unmarshal(m, b)
}
func (m *OrderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatusResponse.Marshal(b, m, deterministic)
}
func (m *OrderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatusResponse.Merge(m, src)
}
func (m *OrderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_OrderStatusResponse.Size(m)
}
func (m *OrderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatusResponse proto.InternalMessageInfo

func (m *OrderStatusResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderStatusResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrderStatusResponse) GetUserCredentials() *UserCredentials {
	if m != nil {
		return m.UserCredentials
	}
	return nil
}

func (m *OrderStatusResponse) GetOrder() *OrderAndExchangeType {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrdersStatusesRequest struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrdersDescriptors    []*OrderDescriptorType `protobuf:"bytes,3,rep,name=orders_descriptors,json=ordersDescriptors,proto3" json:"orders_descriptors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OrdersStatusesRequest) Reset()         { *m = OrdersStatusesRequest{} }
func (m *OrdersStatusesRequest) String() string { return proto.CompactTextString(m) }
func (*OrdersStatusesRequest) ProtoMessage()    {}
func (*OrdersStatusesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{3}
}

func (m *OrdersStatusesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersStatusesRequest.Unmarshal(m, b)
}
func (m *OrdersStatusesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersStatusesRequest.Marshal(b, m, deterministic)
}
func (m *OrdersStatusesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersStatusesRequest.Merge(m, src)
}
func (m *OrdersStatusesRequest) XXX_Size() int {
	return xxx_messageInfo_OrdersStatusesRequest.Size(m)
}
func (m *OrdersStatusesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersStatusesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersStatusesRequest proto.InternalMessageInfo

func (m *OrdersStatusesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrdersStatusesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrdersStatusesRequest) GetOrdersDescriptors() []*OrderDescriptorType {
	if m != nil {
		return m.OrdersDescriptors
	}
	return nil
}

type OrdersStatusesResponse struct {
	Id                   string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Order                []*OrderAndExchangeType `protobuf:"bytes,4,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OrdersStatusesResponse) Reset()         { *m = OrdersStatusesResponse{} }
func (m *OrdersStatusesResponse) String() string { return proto.CompactTextString(m) }
func (*OrdersStatusesResponse) ProtoMessage()    {}
func (*OrdersStatusesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{4}
}

func (m *OrdersStatusesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersStatusesResponse.Unmarshal(m, b)
}
func (m *OrdersStatusesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersStatusesResponse.Marshal(b, m, deterministic)
}
func (m *OrdersStatusesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersStatusesResponse.Merge(m, src)
}
func (m *OrdersStatusesResponse) XXX_Size() int {
	return xxx_messageInfo_OrdersStatusesResponse.Size(m)
}
func (m *OrdersStatusesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersStatusesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersStatusesResponse proto.InternalMessageInfo

func (m *OrdersStatusesResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrdersStatusesResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *OrdersStatusesResponse) GetOrder() []*OrderAndExchangeType {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrderByUserCredentials struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserCredentials      *UserCredentials `protobuf:"bytes,2,opt,name=user_credentials,json=userCredentials,proto3" json:"user_credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetOrderByUserCredentials) Reset()         { *m = GetOrderByUserCredentials{} }
func (m *GetOrderByUserCredentials) String() string { return proto.CompactTextString(m) }
func (*GetOrderByUserCredentials) ProtoMessage()    {}
func (*GetOrderByUserCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{5}
}

func (m *GetOrderByUserCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderByUserCredentials.Unmarshal(m, b)
}
func (m *GetOrderByUserCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderByUserCredentials.Marshal(b, m, deterministic)
}
func (m *GetOrderByUserCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderByUserCredentials.Merge(m, src)
}
func (m *GetOrderByUserCredentials) XXX_Size() int {
	return xxx_messageInfo_GetOrderByUserCredentials.Size(m)
}
func (m *GetOrderByUserCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderByUserCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderByUserCredentials proto.InternalMessageInfo

func (m *GetOrderByUserCredentials) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetOrderByUserCredentials) GetUserCredentials() *UserCredentials {
	if m != nil {
		return m.UserCredentials
	}
	return nil
}

type GetOrdersByUserCredentialsResponse struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Orders               []*OrderAndUserCredentials `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetOrdersByUserCredentialsResponse) Reset()         { *m = GetOrdersByUserCredentialsResponse{} }
func (m *GetOrdersByUserCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersByUserCredentialsResponse) ProtoMessage()    {}
func (*GetOrdersByUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb21f6ae3f6980d6, []int{6}
}

func (m *GetOrdersByUserCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersByUserCredentialsResponse.Unmarshal(m, b)
}
func (m *GetOrdersByUserCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersByUserCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersByUserCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersByUserCredentialsResponse.Merge(m, src)
}
func (m *GetOrdersByUserCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersByUserCredentialsResponse.Size(m)
}
func (m *GetOrdersByUserCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersByUserCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersByUserCredentialsResponse proto.InternalMessageInfo

func (m *GetOrdersByUserCredentialsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetOrdersByUserCredentialsResponse) GetOrders() []*OrderAndUserCredentials {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*PlaceOrderRequest)(nil), "orders.v1.PlaceOrderRequest")
	proto.RegisterType((*OrderStatusRequest)(nil), "orders.v1.OrderStatusRequest")
	proto.RegisterType((*OrderStatusResponse)(nil), "orders.v1.OrderStatusResponse")
	proto.RegisterType((*OrdersStatusesRequest)(nil), "orders.v1.OrdersStatusesRequest")
	proto.RegisterType((*OrdersStatusesResponse)(nil), "orders.v1.OrdersStatusesResponse")
	proto.RegisterType((*GetOrderByUserCredentials)(nil), "orders.v1.GetOrderByUserCredentials")
	proto.RegisterType((*GetOrdersByUserCredentialsResponse)(nil), "orders.v1.GetOrdersByUserCredentialsResponse")
}

func init() {
	proto.RegisterFile("orders/v1/orders_service.proto", fileDescriptor_cb21f6ae3f6980d6)
}

var fileDescriptor_cb21f6ae3f6980d6 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0x9d, 0xfe, 0xf9, 0xc9, 0x54, 0xd0, 0x76, 0x11, 0xc1, 0x18, 0x28, 0xc1, 0xe2, 0xd0,
	0x03, 0xd8, 0x6d, 0x11, 0x97, 0xc2, 0x85, 0x86, 0x0a, 0x55, 0x40, 0xa9, 0x0c, 0xbd, 0x70, 0x89,
	0x1c, 0xef, 0x28, 0xb5, 0xe4, 0x78, 0xcd, 0xee, 0x3a, 0xb4, 0x4f, 0xc1, 0xb3, 0x70, 0xe7, 0x1d,
	0x78, 0x10, 0x5e, 0x02, 0x65, 0xd7, 0x71, 0x6c, 0x27, 0x41, 0x8d, 0xa8, 0xe0, 0x66, 0xcf, 0x7e,
	0x33, 0xf3, 0x7d, 0xdf, 0x8c, 0xd7, 0xb0, 0xc5, 0x38, 0x45, 0x2e, 0xbc, 0xd1, 0xae, 0xa7, 0x9f,
	0x7a, 0x02, 0xf9, 0x28, 0x0a, 0xd1, 0x4d, 0x39, 0x93, 0x8c, 0xb4, 0x74, 0xd4, 0x1d, 0xed, 0xda,
	0xed, 0x3a, 0x54, 0x43, 0x9c, 0x6f, 0x06, 0x6c, 0x9e, 0xc4, 0x41, 0x88, 0xef, 0xc7, 0x51, 0x1f,
	0x3f, 0x67, 0x28, 0x24, 0xb9, 0x01, 0x66, 0x44, 0x2d, 0xa3, 0x63, 0x6c, 0xb7, 0x7c, 0x33, 0xa2,
	0xe4, 0x36, 0xfc, 0x9f, 0x09, 0xe4, 0xbd, 0x88, 0x5a, 0xa6, 0x0a, 0x36, 0xc7, 0xaf, 0x47, 0x94,
	0x1c, 0xc2, 0x86, 0x3a, 0x08, 0x39, 0x52, 0x4c, 0x64, 0x14, 0xc4, 0xc2, 0x6a, 0x74, 0x8c, 0xed,
	0xb5, 0x3d, 0xdb, 0x2d, 0x9a, 0xbb, 0xa7, 0x02, 0x79, 0x77, 0x8a, 0xf0, 0xd7, 0xb3, 0x6a, 0x80,
	0x3c, 0x86, 0xff, 0x14, 0xda, 0x5a, 0x55, 0xb9, 0xed, 0x52, 0x6e, 0x97, 0x63, 0x20, 0x73, 0x76,
	0x1a, 0xe4, 0xfc, 0x30, 0x80, 0xa8, 0xc0, 0x07, 0x19, 0xc8, 0x4c, 0xfc, 0x2b, 0xd2, 0x47, 0xb0,
	0xa1, 0xd0, 0x3d, 0x8a, 0x22, 0xe4, 0x51, 0x2a, 0xd9, 0x84, 0xff, 0x56, 0xa9, 0x8c, 0x22, 0xfa,
	0xaa, 0x40, 0x7c, 0xbc, 0x48, 0xd1, 0x5f, 0x67, 0xd5, 0xa0, 0xf3, 0xdd, 0x80, 0x9b, 0x15, 0x45,
	0x22, 0x65, 0x89, 0xc0, 0xbf, 0x2e, 0xe9, 0x59, 0x75, 0x0e, 0x0f, 0xea, 0x3a, 0x5e, 0x26, 0xf4,
	0xf0, 0x3c, 0x3c, 0x0b, 0x92, 0x01, 0x2a, 0x21, 0xf9, 0x40, 0xbe, 0x1a, 0x70, 0x4b, 0x9d, 0x0b,
	0xcd, 0x1f, 0x97, 0x9f, 0xc9, 0x3b, 0x20, 0xf9, 0x0a, 0x4f, 0xdd, 0x1c, 0x4b, 0x68, 0x5c, 0xc2,
	0xce, 0x4d, 0x7d, 0x3c, 0x8d, 0x0a, 0xe7, 0x1c, 0xda, 0x75, 0x42, 0xcb, 0x5a, 0x5a, 0xf2, 0xa2,
	0xb1, 0x84, 0x17, 0x1c, 0xee, 0xbc, 0x46, 0xa9, 0x10, 0x07, 0x17, 0x35, 0xc3, 0x67, 0x9a, 0xcf,
	0x1b, 0x9b, 0xb9, 0xf4, 0xd8, 0x9c, 0x14, 0x9c, 0x49, 0x4f, 0x31, 0xd3, 0x74, 0xa1, 0xf2, 0x7d,
	0x68, 0xea, 0x1e, 0x96, 0xa9, 0x14, 0x3a, 0x73, 0x14, 0xd6, 0x6b, 0xe5, 0x19, 0x7b, 0x3f, 0x57,
	0xe1, 0x7a, 0x6e, 0xb0, 0xbe, 0x71, 0xc8, 0x5b, 0x80, 0xe9, 0x3d, 0x42, 0xee, 0x95, 0x6a, 0xcd,
	0x5c, 0x2f, 0xf6, 0xcc, 0x40, 0xab, 0x6b, 0xef, 0xac, 0x90, 0x63, 0x58, 0xeb, 0x06, 0x49, 0x88,
	0xb1, 0x2e, 0x77, 0x7f, 0x51, 0xc2, 0x65, 0xeb, 0xbd, 0x81, 0x6b, 0x13, 0x87, 0xfe, 0xbc, 0xd8,
	0x31, 0xb4, 0x4e, 0x58, 0x7c, 0x45, 0xd4, 0x76, 0x0c, 0xe2, 0x43, 0xab, 0x18, 0x1f, 0xe9, 0xd4,
	0x13, 0xea, 0xdf, 0x94, 0xfd, 0xf0, 0x37, 0x88, 0x82, 0xe3, 0x29, 0x40, 0xc1, 0xf1, 0xaa, 0x8a,
	0xee, 0x18, 0x44, 0xc2, 0xdd, 0xb9, 0x9b, 0x96, 0xef, 0xf7, 0xa3, 0x52, 0x95, 0x85, 0x5f, 0x81,
	0xfd, 0x64, 0x0e, 0x6a, 0xf1, 0xde, 0x3a, 0x2b, 0x07, 0x2f, 0x3e, 0xed, 0x0f, 0x22, 0x79, 0x96,
	0xf5, 0xdd, 0x90, 0x0d, 0xbd, 0x2f, 0x01, 0x4f, 0x07, 0xdc, 0x93, 0xb4, 0x1f, 0xf4, 0x42, 0x36,
	0x1c, 0xb2, 0xc4, 0x1b, 0x30, 0x4f, 0xfd, 0xce, 0x42, 0x16, 0x7b, 0xc5, 0x8f, 0xee, 0xb9, 0x7e,
	0xea, 0x37, 0xd5, 0xd1, 0xd3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xbe, 0x48, 0x69, 0x2e,
	0x07, 0x00, 0x00,
}
